//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:36:15 AM ART 
//


package org.cidisi.bpmn.extensions.samples.workdistribution.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.cidisi.bpmn.extensions.samples.workdistribution.AgentType;
import org.cidisi.bpmn.extensions.samples.workdistribution.TaskPrivilege;


/**
 * <p>Java class for WorkDistributionBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkDistributionBinding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.cidisi.org/bpmn/extensions/samples/workdistribution}WorkDistribution"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkDistributionBinding", propOrder = {
    "distributionAgent",
    "taskPrivileges",
    "distributionTrigger"
})
public class WorkDistributionBinding {

    @XmlElement(namespace = "http://www.cidisi.org/bpmn/extensions/samples/workdistribution", required = true)
    protected AgentType distributionAgent;
    @XmlElement(namespace = "http://www.cidisi.org/bpmn/extensions/samples/workdistribution", required = true)
    protected List<TaskPrivilege> taskPrivileges;
    @XmlElement(namespace = "http://www.cidisi.org/bpmn/extensions/samples/workdistribution")
    protected QName distributionTrigger;

    /**
     * Gets the value of the distributionAgent property.
     * 
     * @return
     *     possible object is
     *     {@link AgentType }
     *     
     */
    public AgentType getDistributionAgent() {
        return distributionAgent;
    }

    /**
     * Sets the value of the distributionAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentType }
     *     
     */
    public void setDistributionAgent(AgentType value) {
        this.distributionAgent = value;
    }

    /**
     * Gets the value of the taskPrivileges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskPrivileges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskPrivileges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskPrivilege }
     * 
     * 
     */
    public List<TaskPrivilege> getTaskPrivileges() {
        if (taskPrivileges == null) {
            taskPrivileges = new ArrayList<TaskPrivilege>();
        }
        return this.taskPrivileges;
    }

    /**
     * Gets the value of the distributionTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getDistributionTrigger() {
        return distributionTrigger;
    }

    /**
     * Sets the value of the distributionTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setDistributionTrigger(QName value) {
        this.distributionTrigger = value;
    }

}
